#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

// Usage: node tools/gen-sensor.cjs <count> <output.json>
const args = process.argv.slice(2);

if (args.length < 2) {
  console.error("Usage: node tools/gen-sensor.cjs <count> <output.json>");
  process.exit(1);
}

const countArg = args[0];
const out = args[1];

const count = parseInt(countArg, 10);
if (Number.isNaN(count) || count <= 0) {
  console.error("Invalid count:", countArg);
  process.exit(1);
}

function randn() {
  let u = 0;
  let v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  return Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
}

function clamp(v, min, max) {
  return Math.min(max, Math.max(min, v));
}

function genSeries(kind, base, jitter, range) {
  const min = range[0];
  const max = range[1];
  const start = Date.now();
  const stepMs = 60 * 1000; // 1 minute

  const points = [];
  for (let i = 0; i < count; i++) {
    let value = base + randn() * jitter;
    value = clamp(value, min, max);
    points.push({
      t: start + i * stepMs,
      v: Number(value.toFixed(2))
    });
  }

  return { kind, points };
}

// Profil Korhogo novembre (cajou)
// Donnees meteo basees sur les capteurs installés par la Team Wakama.farm sur le site
const batch = {
  type: "wakama.sensor.batch",
  version: 1,
  source: "external",
  team: "team-scak-coop",
  site: {
    country: "CI",
    zone: "Korhogo",
    locality: "Korhogo",
    field: "scak-korhogo-20ha",
    device: "esp32-scak-001",
    gps: {
      lat: 9.505691,
      lon: -5.688757
    }
  },
  ts: new Date().toISOString(),
  readings: [
    // Temperature de l air (DHT22), environ 27–34 degres
    genSeries("DHT22.tempC", 29.5, 3.0, [22, 38]),

    // Humidite relative de l air (en pourcentage)
    genSeries("DHT22.humidityPct", 50, 15, [20, 90]),

    // Humidite du sol (pourcentage volumique approx)
    genSeries("Soil.moisturePct", 30, 10, [10, 70]),

    // Indices specifiques cajou (0 a 100)
    // Densite de couvert vegetal (vigueur des arbres)
    genSeries("Cashew.canopyIndex", 70, 10, [30, 100]),

    // Intensite de floraison
    genSeries("Cashew.floweringIndex", 55, 15, [0, 100]),

    // Mise a fruits / nouaison
    genSeries("Cashew.nutSetIndex", 40, 12, [0, 100]),

    // Risque ravageurs (perceurs, foreurs, etc.)
    genSeries("Cashew.pestRiskIndex", 20, 10, [0, 100])
  ],
  meta: {
    unitTime: "ms since epoch",
    note: "generated by tools/gen-sensor.cjs (SCAK Korhogo cashew profile, external team)"
  }
};

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(batch, null, 2), "utf8");
console.log(
  `Wrote ${out} with ${count} points per series for team-scak-coop`
);
