#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const N = parseInt(process.argv[2] || '60', 10);
const out = process.argv[3] || 'out/sensor-batch.json';

//
function randn() {
  let u = 0, v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function genSeries(kind, base, noise, bounds) {
  const now = Date.now();
  const points = [];
  for (let i = 0; i < N; i++) {
    let v = base + noise * randn();
    v = Math.max(bounds[0], Math.min(bounds[1], v));
    points.push({
      t: now - (N - 1 - i) * 60_000, // 1 point par minute
      v: Number(v.toFixed(3))
    });
  }
  return { kind, points };
}

const batch = {
  type: 'wakama.sensor.batch',
  version: 1,
  source: 'external',
  team: 'team-makm2',
  site: {
    country: 'CI',
    zone: 'Abidjan',
    locality: 'Anyama',
    field: 'palmafrique-anyama-400ha',
    device: 'drone-mke-001',
    gps: {
      lat: 5.389962,
      lon: -4.191390
    }
  },
  crop: {
    species: 'Elaeis guineensis',
    commonName: 'oil palm',
    plantationType: 'industrial',
    areaHa: 400
  },
  ts: new Date().toISOString(),
  readings: [
    // Air temperature  du couvert,  novembre 15/2025
    genSeries('DHT22.tempC', 27.5, 0.7, [24, 35]),

    // Humidité novembre 15/2025
    genSeries('DHT22.humidityPct', 82, 3.5, [65, 100]),

    // Humidité du sol dans une palmeraie irriguée /  arrosée / novembre 15/2025
    genSeries('Soil.moisturePct', 55, 5, [30, 90]),

    // NDVI de canopée de palmier a huile (plantation en bon etat)
    genSeries('Palm.canopyNDVI', 0.78, 0.03, [0.60, 0.90]),

    // Hauteur moyenne de canopee des palmiers (m)
    genSeries('Palm.canopyHeightM', 11, 0.2, [6, 18]),

    // Indice synthetique de maturite des fruits (0 a 1)
    genSeries('Palm.fruitMaturityIdx', 0.65, 0.08, [0.20, 1.00])
  ],
  meta: {
    unitTime: 'ms since epoch',
    note: 'generated by tools/gen-sensor.cjs (Palmafrique Anyama oil palm profile)'
  }
};

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(batch, null, 2));
console.log('Wrote', out);
