#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

// N = nombre de points par série
const N = parseInt(process.argv[2] || '60', 10);
// Chemin de sortie
const out = process.argv[3] || 'out/sensor-batch-techlab-bingerville.json';

function randn () {
  let u = 0, v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

// Génère une série réaliste pour Bingerville (Abidjan) en novembre
// Températures récentes ~25–31°C, on se cale dessus.
function genSeries (kind, base, noise, bounds) {
  const now = Date.now();
  const points = [];
  for (let i = 0; i < N; i++) {
    let v = base + noise * randn();
    v = Math.max(bounds[0], Math.min(bounds[1], v));
    points.push({
      t: now - (N - 1 - i) * 60_000, // 1 point / minute
      v: Number(v.toFixed(2))
    });
  }
  return { kind, points };
}

const batch = {
  type: 'wakama.sensor.batch',
  version: 1,
  // très important pour Amira : données externes
  source: 'external',
  // identifiant d’équipe pour les métriques
  team: 'team-techlab-cme',
  site: {
    country: 'CI',
    zone: 'Abidjan',
    locality: 'Bingerville',
    field: 'techlab-bingerville-25ha',
    device: 'esp32-techlab-001',
    gps: {
      lat: 5.399230,
      lon: -3.867965
    }
  },
  ts: new Date().toISOString(),
  readings: [
    // Température air (DHT22) ~ 26–30°C, bruit léger
    genSeries('DHT22.tempC', 27.8, 0.7, [24.5, 31.5]),
    // Humidité air (%) ~ 75–95 (côte humide, novembre)
    genSeries('DHT22.humidityPct', 82, 3.0, [70, 98]),
    // Température sol (DS18B20) ~ 24–29°C
    genSeries('DS18B20.soilTempC', 26, 0.6, [23, 30]),
    // Humidité sol (%) ~ 40–60
    genSeries('Soil.moisturePct', 48, 4.0, [30, 70])
  ],
  meta: {
    unitTime: 'ms since epoch',
    note: 'generated by tools/gen-sensor.cjs (Techlab CME Bingerville for Wakama Oracle)',
    team: 'team-techlab-cme',
    organization: 'Techlab CME Bingerville',
    crops: ['tomato', 'eggplant'],
    acreage_ha: 25
  }
};

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(batch, null, 2));
console.log('Wrote', out);
